#! /usr/local/bin/zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "Installation for Linux"
        sudo apt install "$@"
        exit 0
  local DISTRIB=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
  if [[ ${DISTRIB} = "Ubuntu"* ]]; then
    if uname -a | grep -q '^Linux.*Microsoft'; then
        echo "Installation for WSL..."
        sudo apt install "$@"
        exit 0
    else
        echo "Installation for Linux..."
        sudo apt install "$@"
        exit 0
    fi
  elif [[ ${DISTRIB} = "Debian"* ]]; then
        echo "Installation for Debian..."
        sudo apt install "$@"
        exit 0
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Installation for MacOS"
        brew install "$@"
        exit 0
fi
  if [ "$?" != 0 ]; then
        echo "... Nothing was installed"
        exit 1
  fi
exit 0
