#! /usr/local/bin/zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  local DISTRIB=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
  if [[ ${DISTRIB} = "Ubuntu"* ]]; then
    if uname -a | grep -q '^Linux.*Microsoft'; then
    echo "this is wsl"
      # ubuntu via WSL Windows Subsystem for Linux
    else
    echo "this is ubuntu"
      # native ubuntu
    fi
  elif [[ ${DISTRIB} = "Debian"* ]]; then
    echo "this is debian"
    # debian
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "this is macos"
  # macOS OSX
fi
