#!/bin/bash

zsh() {
        echo Installing zsh...

        sudo apt install zsh

        echo Setting zsh as default shell...

        chsh -s $(which zsh)

        echo Installing oh-my-zsh...

        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        source ~/.zshrc

        echo Installing custom zsh stuff...

        git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions

        echo Installing fonts

        git clone https://github.com/powerline/fonts.git --depth=1
        cd fonts
        ./install.sh
        cd ..
        rm -rf fonts
        
        echo Installing oh-my-zsh...
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 


        echo Your new shell is ready!

        exit 0;
}

vim() {

        echo Installing Vim 8.2...

        if [ -f /usr/bin/vim ]; then
                echo Vim already installed
        else
               sudo apt-get install vim
        fi
#        command -v vim >/dev/null 2>&1 || {
 #               sudo apt-get install vim
  #      }
                
                # sudo add-apt-repository ppa:jonathonf/vim

        # sudo apt-get update


        echo Installing Vim Plug...

        # curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        #     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

        # echo Installing Vim plugins...

        # vim -c ":PlugInstall<cr>"

        # echo Done!

        # exit 0;
}

nvm() {

echo Installing NVM...

        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

source ~/.zshrc

echo nvm installed, I assume that you still have the configs in your zshrc...

nvm install --lts
}


for func in "$@"
do
        "$func" 
done
