#!/bin/bash

echo Installing zsh...

sudo apt install zsh

echo Setting zsh as default shell...

chsh -s $(which zsh)

echo Installing oh-my-zsh...

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

source .zshrc

echo Installing custom zsh stuff...

git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions

echo Installing fonts

git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts

echo Your new shell is ready!
