#!/bin/zsh
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

echo "Running Mac setup..."

# ~/.macos — https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Check for Homebrew
if test ! "$(command -v brew)"
then
  echo "Installing Homebrew."
	/bin/zsh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

fi

#echo "Installing Brewfile..."
brew bundle --file=../Brewfile

#installcask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package && qlmanage -r

#sudo easy_install pip
# sudo pip install -r requirements.pip
# installcask install virtualbox
# installcask install vagrant
echo "Installing nvm --lts..."
nvm install --lts
echo "Using lts..."
nvm use --lts
echo "Alias default => lts..."
nvm alias default --lts

brew cleanup && brew cask cleanup
echo "You may have to delete /Library/Preferences/com.apple.Bluetooth.plist or *Bluetooth related filenames and reboot"

source $HOME/.zshenv
source $HOME/.zprofile
source $HOME/.zshrc

echo "Done!"
exit 0
