#! /usr/local/bin/zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "---------------------"
        echo "Uninstallation for Linux / WSL"
        echo "---------------------"
  local DISTRIB=$(awk -F= '/^NAME/{print $2}' /etc/os-release)
  if [[ ${DISTRIB} = "Ubuntu"* ]]; then
    if uname -a | grep -q '^Linux.*Microsoft'; then
        echo "Unistallation for WSL..."
        sudo apt uninstall "$@"
    else
        echo "Unistallation for Linux..."
        sudo apt uninstall "$@"
    fi
  elif [[ ${DISTRIB} = "Debian"* ]]; then
        echo "---------------------"
        echo "Unistallation for Debian..."
        echo "---------------------"
        sudo apt uninstall "$@"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "---------------------"
        echo "Unistallation for MacOS"
        echo "---------------------"
        brew uninstall "$@"
fi
  if [ "$?" != 0 ]; then
        echo "---------------------"
        echo "... Nothing was removed"
        echo "---------------------"
        else
        echo "---------------------"
        echo "Unistallation successfully completed!"
        echo "---------------------"

  fi
exit 0
